In [1]:
import pandas as pd

In [2]:
file = open(file="..\\data\\samplePinyinEdu\\全字庫音檔說明文件.txt", mode="r", encoding="utf-8")
texts = file.read()

texts = texts.split("\n")[texts.split("\n").index("ㄚ\ta"):]
bopomofo_list = list()
bopomofo_non_accent_list = list()
pinyin_edu_list = list()
pinyin_non_accent_list = list()

for text in texts:
    bopomofo = text.split("\t")[0]
    bopomofo_non_accent = ""
    for ch in bopomofo:
        if ch not in ["ˊ", "ˇ", "ˋ", "˙"]:
            bopomofo_non_accent += ch
    pinyin = text.split("\t")[1]
    pinyin_non_accent = pinyin[:-1] if pinyin[-1].isdigit() else pinyin
    bopomofo_list.append(bopomofo)
    bopomofo_non_accent_list.append(bopomofo_non_accent)
    pinyin_edu_list.append(pinyin)
    pinyin_non_accent_list.append(pinyin_non_accent)

df = pd.DataFrame(
    data={
        "bopomofo": bopomofo_list,
        "bopomofo_non_accent": bopomofo_non_accent_list,
        "pinyin": pinyin_edu_list,
        "pinyin_non_accent": pinyin_non_accent_list
    }
)

df

     bopomofo bopomofo_non_accent pinyin pinyin_non_accent
0           ㄚ                   ㄚ      a                 a
1          ㄚˊ                   ㄚ     a2                 a
2          ㄚˋ                   ㄚ     a4                 a
3          ˙ㄚ                   ㄚ     a5                 a
4           ㄞ                   ㄞ     ai                ai
...       ...                 ...    ...               ...
1462      ㄗㄨㄛ                 ㄗㄨㄛ    zuo               zuo
1463     ㄗㄨㄛˊ                 ㄗㄨㄛ   zuo2               zuo
1464     ㄗㄨㄛˇ                 ㄗㄨㄛ   zuo3               zuo
1465     ㄗㄨㄛˋ                 ㄗㄨㄛ   zuo4               zuo
1466     ˙ㄗㄨㄛ                 ㄗㄨㄛ   zuo5               zuo

[1467 rows x 4 columns]

In [3]:
df.to_csv(path_or_buf=".\\edu_pinyin_label_table.csv", index=False)